### ISSUE TITLE
Running the extension source code fails

### ISSUE THREAD

**Issue by alexrainman** [tillig/vscode-spectral#4] opened 2020-03-31 03:08 UTC
Activating extension 'TravisIllig.vscode-spectral' failed: Cannot find module '/Users/alexrainman/Projects/vscode-spectral/client/extension' Require stack: - /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.

**Comment by tillig** [comment] 2020-03-31 03:16
Can you give me more info on what you're doing? It looks like you checked out the code rather than installing it... Did you read the CONTRIBUTING.md doc to see how to build it? What steps are you taking to get this error?

**Comment by alexrainman** [comment] 2020-03-31 03:21
I downloaded the source code and i am debugging it in VS Code with F5. I am validating if this can customized to include a Swagger Preview like vs-swagger-viewer does. If you can do that, then this extension will be perfect.

**Comment by alexrainman** [comment] 2020-03-31 03:22
https://github.com/arjun-g/vs-swagger-viewer/tree/master/src/preview

**Comment by alexrainman** [comment] 2020-03-31 03:27
My advice is to use https://www.npmjs.com/package/swagger-ui-dist

**Comment by alexrainman** [comment] 2020-03-31 03:27
So, no extra validation happens, just a previewer.

**Comment by tillig** [comment] 2020-03-31 03:47
I would recommend looking at the CONTRIBUTING doc and using the instructions there to build before trying to debug. You won't be able to just open it from scratch and start debugging without doing the build as outlined in that doc.

I will say - I won't be adding a previewer to this extension for a couple reasons:

- I'm working with the Spectral team and they may be taking this over. They don't have a previewer in their stuff.
- Spectral lints more than just OpenAPI specs, so there would be some odd behavior if we didn't try to enable or disable based on doc type and validity. It's not quite as easy as just adding a preview.

Try following the build instructions. If that doesn't work, help me reproduce the issue by providing more detail and I'll see what I can do.

Or if, based on what I mentioned, this isn't interesting to pursue anymore, let's close the issue.

Thanks!

**Closed as completed** 2020-03-31 22:29 UTC
